
[[_modules]]
= Modules
:subproject-base: {rootdir}/subprojects/griffon-fatcowicons-
:java-source: /src/main/java/
:groovy-source: /src/main/groovy/
:package-base: org/codehaus/griffon/runtime/
:numbered:

The following sections display all bindings per module. Use this information to
successfully override a binding on your own modules or to troubleshoot a module
binding if the wrong type has been applied by the Griffon runtime.

== JavaFX

Module name: `fatcowicons-javafx-groovy`

Depends on: `javafx-groovy`

[source,java,options="nowrap"]
----
include::{subproject-base}javafx-groovy{groovy-source}{package-base}/javafx/fatcowicons/FatcowIconsJavaFXGroovyModule.java[tags=bindings,indent=0]
----

The following nodes will become available on a Groovy View

[options="2*,header"]
|===
| Node     | Type
| fatcowIcon | `{api_link_fatcowicon_javafx}`
|===

== Swing

Module name: `fatcowicons-swing-groovy`

Depends on: `swing-groovy`

[source,java,options="nowrap"]
----
include::{subproject-base}swing-groovy{java-source}{package-base}/swing/fatcowicons/FatcowIconsSwingGroovyModule.java[tags=bindings,indent=0]
----

The following nodes will become available on a Groovy View

[options="2*,header"]
|===
| Node     | Type
| fatcowIcon | `{api_link_fatcowicon_swing}`
|===

Both `fatcowIcon` Nodes support the following properties

icon:: The name of the icon, such as `rss` or `atm`.
size:: The size of the icon. Either `16` or `32`.

